/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controle.TextPrompt;
import javax.swing.JOptionPane;
import Controle.ControloBD;
import Modelo.Exporter;
import Modelo.ModeloPDF;
import Modelo.ModeloTabela;
import Modelo.StampPageXofY;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gonga
 */
public class ListarFatura extends javax.swing.JFrame {

    ControloBD liga = new ControloBD();
    String select;

    /**
     * Creates new form ListarUtilizador
     */
    public ListarFatura() {
        initComponents();

//        this.select = "select * from colaborador";
//        PreencherTabela("select * from colaborador order by idcolaborador");
    }

    public ListarFatura(String fatura, String caminho) {
        initComponents();
        liga.setCaminho(caminho);

        if (fatura.equals("Fatura")) {
            PreencherTabelaFatura("select * from fatura order by idfactura");
        } else if (fatura.equals("Proforma")) {
            PreencherTabelaProforma("select * from proforma order by idproforma");
        } else if (fatura.equals("Fatura recibo")) {
            PreencherTabela("select * from recibo order by idfatura_recibo");
        } else if (fatura.equals("Liquidação")) {
            PreencherTabelaLiquidacao("select * from liquidacao ;");
        }
        else if (fatura.equals("Orçamentos")) {
            PreencherTabelaOrcamento("select * from orcamento;");
        }
        this.jLabel22.setText(fatura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel_Utilizadores = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Tabela = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jInternalFrame1.setVisible(true);

        jPanel_Utilizadores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_Utilizadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(27, 167, 125));

        jLabel22.setFont(new java.awt.Font("David", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Fatura");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Utilizadores.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1080, -1));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        T_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome de utilizador", "Telefone", "Último login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        T_Tabela.setToolTipText("Ver os dados completos das faturas, recibos, proformas ou as liquidações");
        T_Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(T_Tabela);

        jPanel22.setToolTipText("Actualizar");
        jPanel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel22.setOpaque(false);
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_repeat_90px.png"))); // NOI18N
        jLabel35.setText("jLabel28");

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Actualizar");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.setToolTipText("Emitir um relatório dos dados presentes na tabela em  em PDF ");
        jPanel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel23.setOpaque(false);
        jPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel23MouseClicked(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_pdf_2_90px.png"))); // NOI18N
        jLabel37.setText("jLabel28");

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Exportar PDF");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24.setToolTipText("Emitir um relatório dos dados presentes na tabela em PDF e Imprimir");
        jPanel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel24.setOpaque(false);
        jPanel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel24MouseClicked(evt);
            }
        });

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_print_90px.png"))); // NOI18N
        jLabel39.setText("jLabel28");

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Exportar e Imprimir");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel25.setToolTipText("Emitir um relatório dos dados presentes na tabela em EXEL");
        jPanel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel25.setOpaque(false);
        jPanel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel25MouseClicked(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_exe_90px.png"))); // NOI18N
        jLabel41.setText("jLabel28");

        jLabel42.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Exportar EXEL");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel26.setToolTipText("Voltar");
        jPanel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel26.setOpaque(false);
        jPanel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel26MouseClicked(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_repeat_90px.png"))); // NOI18N
        jLabel43.setText("jLabel28");

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Voltar");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
        );

        jPanel_Utilizadores.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 56, 1080, 520));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Utilizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 965, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Utilizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 470, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
        new ListarFatura(this.jLabel22.getText(), liga.getCaminho()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel22MouseClicked

    private void jPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel23MouseClicked
        if (T_Tabela.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf (.pdf)", "pdf");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Arquivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                String file = chooser.getSelectedFile().toString().concat(".pdf");
                try {
                    ModeloPDF e = new ModeloPDF(new File(file), T_Tabela, "Relatório", liga.getCaminho());
                    if (this.jLabel22.getText().equals("Fatura")) {
                        
                        e.exportA4Fatura(false);
                    }
                    if (this.jLabel22.getText().equals("Fatura recibo")) {
                        e.exportA4Recibo(false);
                    }
                    if (this.jLabel22.getText().equals("Proforma")) {
                        e.exportA4Proforma("das proformas",false);
                    }
                    if (this.jLabel22.getText().equals("Liquidação")) {
                        e.exportA4Liquidacao(false);
                    }
                    else {
                        e.exportA4Proforma("dos orçamentos",false);
                    }

                    JOptionPane.showMessageDialog(null, "Os Dados Foram Gravados no Directorio Selecionado", "Mensagem de Informação", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro durante a exportação.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jPanel23MouseClicked

    private void jPanel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MouseClicked
        if (T_Tabela.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf (.pdf)", "pdf");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Arquivo");
            chooser.setAcceptAllFileFilterUsed(true);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                String file = chooser.getSelectedFile().toString().concat(".pdf");
                try {
                    ModeloPDF e = new ModeloPDF(new File(file), T_Tabela, "Relatório", liga.getCaminho());
                    if (this.jLabel22.getText().equals("Fatura")) {
                        e.exportA4Fatura(true);
                    }
                    if (this.jLabel22.getText().equals("Fatura recibo")) {
                        e.exportA4Recibo(true);
                    }
                    if (this.jLabel22.getText().equals("Proforma")) {
                        e.exportA4Proforma("das proformas",true);
                    }
                    if (this.jLabel22.getText().equals("Liquidação")) {
                        e.exportA4Liquidacao(true);
                    }
                    if (this.jLabel22.getText().equals("Orçamentos")) {
                        e.exportA4Proforma("dos orçamentos",true);
                    }

                    JOptionPane.showMessageDialog(null, "Os Dados Foram Gravados no Directorio Selecionado", "Mensagem de Informação", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro durante a exportação.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jPanel24MouseClicked

    private void jPanel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel25MouseClicked
        if (T_Tabela.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel (.xls)", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Arquivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {

                List<JTable> tb = new ArrayList<JTable>();
                List<String> nom = new ArrayList<String>();
                tb.add(T_Tabela);
                nom.add("Relatório das " + this.jLabel22.getText());
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Os Dados Foram Gravados no Directorio Selecionado", "Mensagem de Informação", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro na exportação.", " Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jPanel25MouseClicked

    private void T_TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_TabelaMouseClicked
        int linha = T_Tabela.getSelectedRow();
        String idFat;
        if (linha != -1) {
            idFat = T_Tabela.getValueAt(linha, 0).toString();
            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(rootPane, "Deseja rever o documento " + idFat + "?", "", JOptionPane.YES_NO_OPTION)) {
                if (jLabel22.getText().equals("Fatura")) 
                    this.liga.Abrir_Doc("fatura", "idfactura", idFat);
               
                if (jLabel22.getText().equals("Proforma")) 
                     this.liga.Abrir_Doc("proforma", "idproforma", idFat);
               
                if (jLabel22.getText().equals("Fatura recibo")) 
                     this.liga.Abrir_Doc("recibo", "idfatura_recibo", idFat);
               
                if (jLabel22.getText().equals("Liquidação")) 
                     this.liga.Abrir_Doc("liquidacao", "idliquidacao", idFat);
                if (jLabel22.getText().equals("Orçamentos")) 
                     this.liga.Abrir_Doc("orcamento", "idorcamento", idFat);
               
            }
        }
    }//GEN-LAST:event_T_TabelaMouseClicked

    private void jPanel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel26MouseClicked
        // TODO add your handling code here:dsd
        PreencherTabela("select * from recibo order by idfatura_recibo");
    }//GEN-LAST:event_jPanel26MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarFatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable T_Tabela;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel_Utilizadores;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void PreencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"id","Nº Doc", "Desc.(Kz)", "Data", "Hora", "Ret. Fonte", "Total(Kz)", "Pagamento(Kz)", "troco"};
        liga.conexao();
        liga.executeSql(Sql);

        try {
            liga.rs.first();
            do {
                 int aux = liga.rs.getInt("idfatura_recibo");
                String num_do_doc;
                if (aux<10)
                   num_do_doc = "FR "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" 0"+aux;
                else  
                   num_do_doc = "FR "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" "+aux;
                
                dados.add(new Object[]{liga.rs.getString("idfatura_recibo"),num_do_doc, liga.Chang(liga.rs.getString("desconto")), liga.rs.getString("data"), liga.rs.getString("hora"), 
                    liga.Chang(liga.rs.getString("retencao_na_fonte")), liga.Chang(liga.rs.getString("total")), liga.Chang(liga.rs.getString("valor_pago")), liga.Chang(liga.rs.getString("Troco"))});
            } while (liga.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dados não encntrados", null, JOptionPane.WARNING_MESSAGE);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
        };
        T_Tabela.setModel(modelo);
        T_Tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
        T_Tabela.getColumnModel().getColumn(0).setResizable(true);
        T_Tabela.getColumnModel().getColumn(1).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(1).setResizable(true);
        T_Tabela.getColumnModel().getColumn(2).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(2).setResizable(true);
        T_Tabela.getColumnModel().getColumn(3).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(3).setResizable(true);
        T_Tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(4).setResizable(true);
        T_Tabela.getColumnModel().getColumn(5).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(5).setResizable(true);
        T_Tabela.getColumnModel().getColumn(6).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(6).setResizable(true);
        T_Tabela.getColumnModel().getColumn(7).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(7).setResizable(true);
        T_Tabela.getColumnModel().getColumn(8).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(8).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(9).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(9).setResizable(false);

        T_Tabela.getTableHeader().setReorderingAllowed(false);
        T_Tabela.setAutoResizeMode(T_Tabela.AUTO_RESIZE_ALL_COLUMNS);
//        JTableColaboradores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        liga.deconecta();
    }

    public void PreencherTabelaFatura(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nº Doc", "Desc.(Kz)", "Data", "Hora", "Ret. Fonte", "Dívida(Kz)", "Liquidação(%)"};
        liga.conexao();
        liga.executeSql(Sql);

        try {
            liga.rs.first();
            do {
                int aux = liga.rs.getInt("idfactura");
                String num_do_doc;
                if (aux<10)
                    num_do_doc = "FT "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" 0"+aux;
                else  
                   num_do_doc = "FT "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" "+aux;
//                dados.add(new Object[]{liga.rs.getString("idfactura"), liga.rs.getString("titulo_da_fatura"), liga.rs.getString("desconto"), liga.rs.getString("data"), liga.rs.getString("hora"), liga.rs.getString("retencao_na_fonte"), liga.rs.getString("total"), liga.rs.getString("liquidacao")});

                dados.add(new Object[]{liga.rs.getString("idfactura"),num_do_doc, liga.Chang(liga.rs.getString("desconto")), 
                    liga.rs.getString("data"), liga.rs.getString("hora"), 
                    liga.Chang(liga.rs.getString("retencao_na_fonte")), liga.Chang(liga.rs.getString("total"))
                        , liga.Chang(liga.rs.getString("liquidacao"))});
            } while (liga.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dados não encntrados", null, JOptionPane.WARNING_MESSAGE);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
        };
        T_Tabela.setModel(modelo);
        T_Tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
        T_Tabela.getColumnModel().getColumn(0).setResizable(true);
        T_Tabela.getColumnModel().getColumn(1).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(1).setResizable(true);
        T_Tabela.getColumnModel().getColumn(2).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(2).setResizable(true);
        T_Tabela.getColumnModel().getColumn(3).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(3).setResizable(true);
        T_Tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(4).setResizable(true);
        T_Tabela.getColumnModel().getColumn(5).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(5).setResizable(true);
        T_Tabela.getColumnModel().getColumn(6).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(6).setResizable(true);
        T_Tabela.getColumnModel().getColumn(7).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(7).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(8).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(8).setResizable(false);
//        JTableColaboradores.getColumnModel().getColumn(9).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(9).setResizable(false);

        T_Tabela.getTableHeader().setReorderingAllowed(false);
        T_Tabela.setAutoResizeMode(T_Tabela.AUTO_RESIZE_ALL_COLUMNS);
//        JTableColaboradores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        liga.deconecta();
    }
    public void PreencherTabelaProforma(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Nº Doc", "Desc.(Kz)", "Data", "Hora", "Ret. Fonte", "Total(Kz)"};
        liga.conexao();
        liga.executeSql(Sql);

        try {
            liga.rs.first();
            do {
                int aux = liga.rs.getInt("idproforma");
                String num_do_doc;
                if (aux<10)
                    num_do_doc = "PP "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" 0"+aux;
                else  
                   num_do_doc = "PP "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" "+aux;

                dados.add(new Object[]{liga.rs.getString("idproforma"), num_do_doc, liga.Chang(liga.rs.getString("desconto")), 
                    liga.rs.getString("data"), liga.rs.getString("hora"), 
                    liga.Chang(liga.rs.getString("retencao_na_fonte")), 
                    liga.Chang(liga.rs.getString("total"))});
            } while (liga.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dados não encntrados", null, JOptionPane.WARNING_MESSAGE);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
        };
        T_Tabela.setModel(modelo);
        T_Tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
        T_Tabela.getColumnModel().getColumn(0).setResizable(true);
        T_Tabela.getColumnModel().getColumn(1).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(1).setResizable(true);
        T_Tabela.getColumnModel().getColumn(2).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(2).setResizable(true);
        T_Tabela.getColumnModel().getColumn(3).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(3).setResizable(true);
        T_Tabela.getColumnModel().getColumn(4).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(4).setResizable(true);
        T_Tabela.getColumnModel().getColumn(5).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(5).setResizable(true);
        T_Tabela.getColumnModel().getColumn(6).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(6).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(7).setPreferredWidth(100);
//        JTableColaboradores.getColumnModel().getColumn(7).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(8).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(8).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(9).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(9).setResizable(false);

        T_Tabela.getTableHeader().setReorderingAllowed(false);
        T_Tabela.setAutoResizeMode(T_Tabela.AUTO_RESIZE_ALL_COLUMNS);
//        JTableColaboradores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        liga.deconecta();
    }
    public void PreencherTabelaOrcamento(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nº Doc", "Desc.(Kz)", "Data", "Hora", "Ret. Fonte", "Total(Kz)"};;
        liga.conexao();
        liga.executeSql(Sql);

        try {
            liga.rs.first();
            do {
                int aux = liga.rs.getInt("idorcamento");
                String num_do_doc;
                if (aux<10)
                    num_do_doc = "OR "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" 0"+liga.rs.getString("idorcamento");
                else  
                   num_do_doc = "OR "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" "+liga.rs.getString("idorcamento");

                dados.add(new Object[]{liga.rs.getString("idorcamento"), num_do_doc, 
                    liga.Chang(liga.rs.getString("desconto")), 
                    liga.rs.getString("data"), liga.rs.getString("hora"), 
                    liga.Chang(liga.rs.getString("retencao_na_fonte")), liga.Chang(liga.rs.getString("total"))});
            } while (liga.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dados não encntrados", null, JOptionPane.WARNING_MESSAGE);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
        };
        T_Tabela.setModel(modelo);
        T_Tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
        T_Tabela.getColumnModel().getColumn(0).setResizable(true);
        T_Tabela.getColumnModel().getColumn(1).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(1).setResizable(true);
        T_Tabela.getColumnModel().getColumn(2).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(2).setResizable(true);
        T_Tabela.getColumnModel().getColumn(3).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(3).setResizable(true);
        T_Tabela.getColumnModel().getColumn(4).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(4).setResizable(true);
        T_Tabela.getColumnModel().getColumn(5).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(5).setResizable(true);
        T_Tabela.getColumnModel().getColumn(6).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(6).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(7).setPreferredWidth(100);
//        JTableColaboradores.getColumnModel().getColumn(7).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(8).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(8).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(9).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(9).setResizable(false);

        T_Tabela.getTableHeader().setReorderingAllowed(false);
        T_Tabela.setAutoResizeMode(T_Tabela.AUTO_RESIZE_ALL_COLUMNS);
//        JTableColaboradores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        liga.deconecta();
    }

    public void PreencherTabelaLiquidacao(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nº", "Nº Doc", "Obectivo", "Observacao", "Data e Hora", "Valor da liquidação(Kz)", "Referente a fatura Nº", "Total a liquidar(Kz)"};
        liga.conexao();
        liga.executeSql(Sql);
       
        try {
            liga.rs.first();
            do {
                 int aux = liga.rs.getInt("idliquidacao");
                String num_do_doc;
                if (aux<10)
                    num_do_doc = "RC "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" 0"+aux;
                else  
                   num_do_doc = "RC "+liga.rs.getString("serie")+" "+liga.rs.getString("indicativo")+" "+aux;
//                dados.add(new Object[]{liga.rs.getString("idfactura"), liga.rs.getString("titulo_da_fatura"), liga.rs.getString("desconto"), liga.rs.getString("data"), liga.rs.getString("hora"), liga.rs.getString("retencao_na_fonte"), liga.rs.getString("total"), liga.rs.getString("liquidacao")});

                dados.add(new Object[]{liga.rs.getString("idliquidacao"), num_do_doc, 
                    liga.rs.getString("objectivo"), liga.rs.getString("observacao"), 
                    liga.rs.getString("data")+"\n"+liga.rs.getString("hora"), 
                    liga.rs.getString("valor"), 
                    liga.rs.getString("idfatura"), 
                    "-"});
            } while (liga.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dados não encntrados", null, JOptionPane.WARNING_MESSAGE);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
        };
        T_Tabela.setModel(modelo);
        T_Tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
        T_Tabela.getColumnModel().getColumn(0).setResizable(true);
        T_Tabela.getColumnModel().getColumn(1).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(1).setResizable(true);
        T_Tabela.getColumnModel().getColumn(2).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(2).setResizable(true);
        T_Tabela.getColumnModel().getColumn(3).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(3).setResizable(true);
        T_Tabela.getColumnModel().getColumn(4).setPreferredWidth(140);
        T_Tabela.getColumnModel().getColumn(4).setResizable(true);
        T_Tabela.getColumnModel().getColumn(5).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(5).setResizable(true);
        T_Tabela.getColumnModel().getColumn(6).setPreferredWidth(180);
        T_Tabela.getColumnModel().getColumn(6).setResizable(true);
        T_Tabela.getColumnModel().getColumn(7).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(7).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(8).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(8).setResizable(true);
//        JTableColaboradores.getColumnModel().getColumn(9).setPreferredWidth(160);
//        JTableColaboradores.getColumnModel().getColumn(9).setResizable(false);

        T_Tabela.getTableHeader().setReorderingAllowed(false);
        T_Tabela.setAutoResizeMode(T_Tabela.AUTO_RESIZE_ALL_COLUMNS);
//        JTableColaboradores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        liga.deconecta();
    }

    public void PreencherTabelaVendas(String Sql) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Tipo", "Descrição", "Preco unitário(Kz)", "Quant.", "Total(Kz)", "IVA", "motivo", "Pagamento(Kz)", "troco"};
        liga.conexao();
        liga.executeSql(Sql);

        try {
            liga.rs.first();
            do {

                dados.add(new Object[]{liga.rs.getString("codigo"), liga.rs.getString("tipo"), liga.rs.getString("descricao"), liga.rs.getString("preco_unitario"), liga.rs.getString("quantidade"), liga.rs.getString("total"), liga.rs.getString("iva"), liga.rs.getString("motivo"), liga.rs.getString("recibo.valor_pago"), liga.rs.getString("recibo.troco")});
            } while (liga.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dados não encntrados", null, JOptionPane.WARNING_MESSAGE);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
        };
        T_Tabela.setModel(modelo);
        T_Tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(0).setResizable(true);
        T_Tabela.getColumnModel().getColumn(1).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(1).setResizable(true);
        T_Tabela.getColumnModel().getColumn(2).setPreferredWidth(200);
        T_Tabela.getColumnModel().getColumn(2).setResizable(true);
        T_Tabela.getColumnModel().getColumn(3).setPreferredWidth(120);
        T_Tabela.getColumnModel().getColumn(3).setResizable(true);
        T_Tabela.getColumnModel().getColumn(4).setPreferredWidth(50);
        T_Tabela.getColumnModel().getColumn(4).setResizable(true);
        T_Tabela.getColumnModel().getColumn(5).setPreferredWidth(120);
        T_Tabela.getColumnModel().getColumn(5).setResizable(true);
        T_Tabela.getColumnModel().getColumn(6).setPreferredWidth(100);
        T_Tabela.getColumnModel().getColumn(6).setResizable(true);
        T_Tabela.getColumnModel().getColumn(7).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(7).setResizable(true);
        T_Tabela.getColumnModel().getColumn(8).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(8).setResizable(true);
        T_Tabela.getColumnModel().getColumn(9).setPreferredWidth(160);
        T_Tabela.getColumnModel().getColumn(9).setResizable(false);

        T_Tabela.getTableHeader().setReorderingAllowed(false);
        T_Tabela.setAutoResizeMode(T_Tabela.AUTO_RESIZE_ALL_COLUMNS);
//        JTableColaboradores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        liga.deconecta();
    }
    
    

}
