/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controle.TextPrompt;
import javax.swing.JOptionPane;
import Controle.ControloBD;
import Controle.Extenso;
import Modelo.ModeloTabela;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Gonga
 */
public class Registo_de_turno extends javax.swing.JFrame {

    ControloBD liga = new ControloBD();
    String select;
    int iduserTuno = -1;
    Extenso exte = new Extenso();
    private int numero =-1;

    /**
     * Creates new form ListarUtilizador
     */
    
    public Registo_de_turno() {
        initComponents();
        Toolkit T = Toolkit.getDefaultToolkit();
        this.setSize(T.getScreenSize());
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }
    public Registo_de_turno(String caminho) {
        initComponents();
        Toolkit T = Toolkit.getDefaultToolkit();
        this.setSize(T.getScreenSize());
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        liga.setCaminho(caminho);
        this.exte.setMeoda(" Kwanza(s)");
        TextPrompt prompt1 = new TextPrompt("Pesquisar", jTextField_Filtrar);
        this.select = "select turno.*, utilizador.*  from turno inner join utilizador "
                + "on turno.idutilizador = utilizador.idutilizador ";

        PreencherTable("select turno.*, utilizador.*  from turno inner join utilizador "
                + "on turno.idutilizador = utilizador.idutilizador "
                + "order by data_entrada desc, hora_entrada desc, "
                + "data_saida desc, horasaida desc");
        this.historico.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel_principal = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jComboBox_OrdenarServico = new javax.swing.JComboBox<String>();
        jPanel22 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox_Filtrar = new javax.swing.JComboBox<String>();
        jTextField_Filtrar = new javax.swing.JTextField();
        jButton_Filtrar = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel_Saldo = new javax.swing.JLabel();
        jLabel_informado = new javax.swing.JLabel();
        jLabel_quebra = new javax.swing.JLabel();
        jLabel_Saldo1 = new javax.swing.JLabel();
        jLabel_informado1 = new javax.swing.JLabel();
        jLabel_quebra1 = new javax.swing.JLabel();
        jLabel_turno = new javax.swing.JLabel();
        jLabel_tuno1 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_todos_turnos = new javax.swing.JTable();
        historico = new javax.swing.JInternalFrame();
        jPanel28 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel_turno4 = new javax.swing.JLabel();
        jLabel_utlilizador3 = new javax.swing.JLabel();
        jLabel_estado_h = new javax.swing.JLabel();
        jLabel_abertura_h = new javax.swing.JLabel();
        jLabel_fecho_h = new javax.swing.JLabel();
        fatura_h = new javax.swing.JLabel();
        recibo_h = new javax.swing.JLabel();
        fatura_recibo_h = new javax.swing.JLabel();
        saida_de_caixa_h = new javax.swing.JLabel();
        saldo_inicial_h = new javax.swing.JLabel();
        bancos_h = new javax.swing.JLabel();
        numerario_h = new javax.swing.JLabel();
        nota_de_pagamento_h = new javax.swing.JLabel();
        nota_de_credito_h = new javax.swing.JLabel();
        entrada_em_caixa_h = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        saldo_atual_h = new javax.swing.JLabel();
        saldo_informado_h = new javax.swing.JLabel();
        jLabel_info = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel_principal.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_principal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Ordenar por");

        jButton6.setText("Ordenar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox_OrdenarServico.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jComboBox_OrdenarServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "numero asc", "numero desc", "estado asc", "estado desc", "data_entrada asc", "data_entrada desc", "hora_entrada asc", "hora_entrada desc", "data_saida asc", "data_saida desc", "horasaida asc", "horasaida desc" }));
        jComboBox_OrdenarServico.setToolTipText("");
        jComboBox_OrdenarServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_OrdenarServicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_OrdenarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_OrdenarServico)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setToolTipText("Atualizar");
        jPanel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel22.setOpaque(false);
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_repeat_90px.png"))); // NOI18N
        jLabel35.setText("jLabel28");

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Actualizar");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Filtrar por");

        jComboBox_Filtrar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jComboBox_Filtrar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nome", "estado", "numero" }));
        jComboBox_Filtrar.setToolTipText("");
        jComboBox_Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FiltrarActionPerformed(evt);
            }
        });

        jTextField_Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FiltrarActionPerformed(evt);
            }
        });

        jButton_Filtrar.setText("Filtar");
        jButton_Filtrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_FiltrarMouseClicked(evt);
            }
        });
        jButton_Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Filtrar, 0, 94, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox_Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Filtrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_principal.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1070, 140));

        jPanel14.setBackground(new java.awt.Color(0, 0, 204));
        jPanel14.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel_Saldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Saldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Saldo.setText("Saldo:");

        jLabel_informado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_informado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_informado.setText("Informado:");

        jLabel_quebra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_quebra.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_quebra.setText("Quebra:");

        jLabel_Saldo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Saldo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Saldo1.setText("0,00 kz");

        jLabel_informado1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_informado1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_informado1.setText("0,00 kz");

        jLabel_quebra1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_quebra1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_quebra1.setText("0,00 kz");

        jLabel_turno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_turno.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_turno.setText("Turno nº");

        jLabel_tuno1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_tuno1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tuno1.setText("0");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_informado)
                            .addComponent(jLabel_Saldo)
                            .addComponent(jLabel_quebra))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_quebra1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(jLabel_informado1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Saldo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel_turno)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_tuno1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_turno)
                    .addComponent(jLabel_tuno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Saldo)
                    .addComponent(jLabel_Saldo1))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_informado1)
                    .addComponent(jLabel_informado))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_quebra)
                    .addComponent(jLabel_quebra1))
                .addContainerGap())
        );

        jPanel_principal.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 650, 190));

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setToolTipText("Ver o hisórico completos do turno.");
        jPanel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel23.setOpaque(false);
        jPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel23MouseClicked(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_historical_90px_1.png"))); // NOI18N
        jLabel37.setText("jLabel28");

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Ver histórico");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_principal.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        jPanel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel24.setToolTipText("Reajustar automaticamenete o turno.");
        jPanel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel24.setOpaque(false);
        jPanel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel24MouseClicked(evt);
            }
        });

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_paid_search_90px.png"))); // NOI18N
        jLabel39.setText("jLabel28");

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Imprimir");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_principal.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, -1, -1));

        jPanel21.setBackground(new java.awt.Color(27, 167, 125));

        jLabel22.setFont(new java.awt.Font("David", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Registo de turno");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_todos_turnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome de utilizador", "Telefone", "Último login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_todos_turnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_todos_turnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_todos_turnos);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        historico.setVisible(true);

        jPanel28.setBackground(new java.awt.Color(27, 167, 125));

        jLabel23.setFont(new java.awt.Font("David", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Histórico do turno");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cramervan/Vista/img/icons8_print_90px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Descrição");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Itens:");

        jLabel_turno4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_turno4.setText("Turno nº");

        jLabel_utlilizador3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_utlilizador3.setText("Utlilizador");

        jLabel_estado_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_estado_h.setText("jLabel21");

        jLabel_abertura_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_abertura_h.setText("jLabel22");

        jLabel_fecho_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_fecho_h.setText("jLabel23");

        fatura_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fatura_h.setText("jLabel24");

        recibo_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        recibo_h.setText("jLabel25");

        fatura_recibo_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fatura_recibo_h.setText("jLabel27");

        saida_de_caixa_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saida_de_caixa_h.setText("jLabel28");

        saldo_inicial_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saldo_inicial_h.setText("jLabel27");

        bancos_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bancos_h.setText("jLabel25");

        numerario_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numerario_h.setText("jLabel24");

        nota_de_pagamento_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nota_de_pagamento_h.setText("jLabel23");

        nota_de_credito_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nota_de_credito_h.setText("jLabel22");

        entrada_em_caixa_h.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        entrada_em_caixa_h.setText("jLabel21");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_turno4)
                    .addComponent(jLabel_utlilizador3)
                    .addComponent(jLabel_estado_h)
                    .addComponent(jLabel_abertura_h)
                    .addComponent(jLabel_fecho_h)
                    .addComponent(fatura_h)
                    .addComponent(recibo_h)
                    .addComponent(fatura_recibo_h)
                    .addComponent(saida_de_caixa_h)
                    .addComponent(entrada_em_caixa_h)
                    .addComponent(nota_de_credito_h)
                    .addComponent(nota_de_pagamento_h)
                    .addComponent(numerario_h)
                    .addComponent(bancos_h)
                    .addComponent(saldo_inicial_h)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel_turno4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_utlilizador3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_estado_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_abertura_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_fecho_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fatura_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recibo_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fatura_recibo_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saida_de_caixa_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrada_em_caixa_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nota_de_credito_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nota_de_pagamento_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numerario_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bancos_h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo_inicial_h)
                .addGap(21, 21, 21))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        saldo_atual_h.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saldo_atual_h.setText("jLabel28");

        saldo_informado_h.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saldo_informado_h.setText("jLabel28");

        jLabel_info.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_info.setText("jLabel15");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saldo_atual_h, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saldo_informado_h, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(saldo_informado_h, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo_atual_h, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jLabel_info, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout historicoLayout = new javax.swing.GroupLayout(historico.getContentPane());
        historico.getContentPane().setLayout(historicoLayout);
        historicoLayout.setHorizontalGroup(
            historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        historicoLayout.setVerticalGroup(
            historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historicoLayout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(historico)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(historico)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FiltrarActionPerformed
        String colum = jComboBox_Filtrar.getSelectedItem().toString();

//        String p = 
        if (colum.equals("numero")) {
            this.select = "select turno.*, utilizador.*  from turno inner join utilizador "
                    + "on turno.idutilizador = utilizador.idutilizador where " + colum + "=" + this.jTextField_Filtrar.getText() + " ";
        } else if (colum.equals("estado") && jTextField_Filtrar.getText().toLowerCase().equals("fechado")) {
            this.select = "select turno.*, utilizador.*  from turno inner join utilizador "
                    + "on turno.idutilizador = utilizador.idutilizador where " + colum + " = false ";
        } else if (colum.equals("estado") && jTextField_Filtrar.getText().toLowerCase().equals("aberto")) {
            this.select = "select turno.*, utilizador.*  from turno inner join utilizador "
                    + "on turno.idutilizador = utilizador.idutilizador where " + colum + " = true ";
        } else {
            this.select = "select turno.*, utilizador.*  from turno inner join utilizador on turno.idutilizador = utilizador.idutilizador "
                    + " where " + colum + " ilike '%" + this.jTextField_Filtrar.getText() + "%' "
                    + " OR nome_utilizador ilike '%" + this.jTextField_Filtrar.getText() + "%' ";
        }

        PreencherTable(select);
//        this.jTextField_Filtrar.setText(colum);
    }//GEN-LAST:event_jButton_FiltrarActionPerformed

    private void jButton_FiltrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_FiltrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_FiltrarMouseClicked

    private void jTextField_FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FiltrarActionPerformed

    private void jComboBox_FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_FiltrarActionPerformed

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
        new Registo_de_turno(liga.getCaminho()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel22MouseClicked

    private void jComboBox_OrdenarServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_OrdenarServicoMouseClicked

    }//GEN-LAST:event_jComboBox_OrdenarServicoMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        System.out.println(this.jComboBox_OrdenarServico.getSelectedItem().toString());
//        System.out.println(this.select + " order by " + this.jComboBox_OrdenarServico.getSelectedItem().toString());
        PreencherTable(this.select + " order by " + this.jComboBox_OrdenarServico.getSelectedItem().toString());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable_todos_turnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_todos_turnosMouseClicked
        int row = this.jTable_todos_turnos.getSelectedRow();
        this.jLabel_tuno1.setText(this.jTable_todos_turnos.getValueAt(row, 0).toString());
        this.Verif(this.jTable_todos_turnos.getValueAt(row, 12).toString(), this.jTable_todos_turnos.getValueAt(row, 13).toString());
    }//GEN-LAST:event_jTable_todos_turnosMouseClicked

    private void jPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel23MouseClicked
        int row = this.jTable_todos_turnos.getSelectedRow();
//        this.jLabel_tuno1.setText(this.jTable_todos_turnos.getValueAt(row, 0).toString());
        if (row != -1) {

            this.iduserTuno = Integer.parseInt(this.jTable_todos_turnos.getValueAt(row, 17).toString());

            if (iduserTuno != -1 && !"0".equals(this.jLabel_tuno1.getText())) {
                liga.conexao();
                liga.executeSql("select *  from turno where numero = " + this.jLabel_tuno1.getText() + " AND  idturno = " + this.iduserTuno + " ");
                try {

                    if (liga.rs.first()) {
                        this.jInternalFrame1.setVisible(false);
                        this.historico.setVisible(true);
                        boolean estado = liga.rs.getBoolean("estado");
//                int numero = ;
                        this.jLabel_turno4.setText("Turno Nº " + liga.rs.getInt("numero"));

                        this.fatura_h.setText("Factura: " + this.exte.Chang(liga.rs.getString("fatura")) + this.exte.getMeoda());
                        this.recibo_h.setText("Recibo: " + this.exte.Chang(liga.rs.getString("recibo")) + this.exte.getMeoda());
                        this.fatura_recibo_h.setText("Factura recibo: " + this.exte.Chang(liga.rs.getString("fatura_recibo")) + this.exte.getMeoda());
                        this.saida_de_caixa_h.setText("Saida de caixa: " + this.exte.Chang(liga.rs.getString("saida_de_caixa")) + this.exte.getMeoda());
                        this.entrada_em_caixa_h.setText("Entrada em caixa: " + this.exte.Chang(liga.rs.getString("entrada_em_caixa")) + this.exte.getMeoda());
                        this.nota_de_credito_h.setText("Nota de credito: " + this.exte.Chang(liga.rs.getString("nota_de_credito")) + this.exte.getMeoda());
                        this.nota_de_pagamento_h.setText("Nota de pagamento: " + this.exte.Chang(liga.rs.getString("nota_de_pagamento")) + this.exte.getMeoda());
                        this.numerario_h.setText("Numerário: " + this.exte.Chang(liga.rs.getString("numerario")) + this.exte.getMeoda());
                        this.bancos_h.setText("Banco: " + this.exte.Chang(liga.rs.getString("bancos")) + this.exte.getMeoda());
                        this.saldo_inicial_h.setText("Saldo inicial: " + this.exte.Chang(liga.rs.getString("saldo_inicial")) + this.exte.getMeoda());
                        double vaIfo, valAtu;
                        vaIfo = liga.rs.getDouble("saldo_final");
                        valAtu = liga.rs.getDouble("saldo_atual");
                        this.saldo_informado_h.setText("Valor informado: " + this.exte.Chang(liga.rs.getString("saldo_final")) + this.exte.getMeoda());
                        this.saldo_atual_h.setText("Saldo: " + this.exte.Chang(liga.rs.getString("saldo_atual")) + this.exte.getMeoda());

                        if (estado) {
                            this.jLabel_estado_h.setText("Estado: Aberto");
                            this.jLabel_abertura_h.setText("Data de abertura: " + liga.rs.getString("data_entrada") + " " + liga.rs.getString("hora_entrada"));
                            this.jLabel_fecho_h.setText("_");
//                    JOptionPane.showMessageDialog(null, "O turno Nº " + numero + " já se encontra aberto.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
//                    this.jButton1.setEnabled(false);
//                    this.jButton2.setEnabled(true);
                            this.saldo_informado_h.setVisible(false);
                            this.jLabel_info.setVisible(false);
                        } else {
//                    new abrir_turno(id_turno,numero,this.id);
                            this.saldo_informado_h.setVisible(true);
                            this.jLabel_info.setVisible(true);
                            double result = vaIfo - valAtu;
                            if (vaIfo > valAtu) {
                                this.jLabel_info.setText("Resultado: " + this.exte.Chang(result) + this.exte.getMeoda() + " Valor em Excesso");
                            } else if (vaIfo < valAtu) {

                                this.jLabel_info.setText("Resultado: " + this.exte.Chang(result) + this.exte.getMeoda() + " Valor em Falta");
                            } else {
                                this.jLabel_info.setText("Resultado: " + this.exte.Chang(result) + this.exte.getMeoda() + " ");
                            }
//                    this.jButton1.setEnabled(true);
//                    this.jButton2.setEnabled(false);
                            this.jLabel_estado_h.setText("Estado: Fechado");
                            this.jLabel_abertura_h.setText("Data de abertura: " + liga.rs.getString("data_entrada") + " " + liga.rs.getString("hora_entrada"));
                            this.jLabel_fecho_h.setText("Data de fecho: " + liga.rs.getString("data_saida") + " " + liga.rs.getString("horasaida"));

                        }

                    } else {
                        this.jInternalFrame1.setVisible(true);
                        this.historico.setVisible(false);
                        this.saldo_informado_h.setVisible(false);
                        this.jLabel_info.setVisible(false);
                        this.jLabel_estado_h.setText("Estado: Fechado");
                        this.jLabel_abertura_h.setText("_");
                        this.jLabel_fecho_h.setText("_");
                        this.fatura_h.setText("_");
                        this.recibo_h.setText("_");
                        this.fatura_recibo_h.setText("_");
                        this.saida_de_caixa_h.setText("_");
                        this.entrada_em_caixa_h.setText("_");
                        this.nota_de_credito_h.setText("_");
                        this.nota_de_pagamento_h.setText("_");
                        this.numerario_h.setText("Numerário: 0");
                        this.bancos_h.setText("Banco: 0");
                        this.saldo_inicial_h.setText("Saldo inicial: 0");
                        this.saldo_atual_h.setText("Saldo: 0");
//                this.jButton1.setEnabled(true);
//                this.jButton2.setEnabled(false);

                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex, "Erro: Consulte o suporte técnico do aplicativo", JOptionPane.ERROR_MESSAGE);
                }
            }
            liga.deconecta();
        } else {
            JOptionPane.showMessageDialog(null, "Seleciona um turno na tabela", "Aviso", JOptionPane.WARNING_MESSAGE);
            jTable_todos_turnos.requestFocus();
        }
    }//GEN-LAST:event_jPanel23MouseClicked

    private void jPanel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MouseClicked
        int row = this.jTable_todos_turnos.getSelectedRow();
        if (row>-1)
        {
            this.iduserTuno = Integer.parseInt(this.jTable_todos_turnos.getValueAt(row, 17).toString());
            this.jLabel_tuno1.setText(this.jTable_todos_turnos.getValueAt(row, 0).toString());
            new FecharTurno(this.iduserTuno, Double.parseDouble(this.jTable_todos_turnos.getValueAt(row, 13).toString()), 
                    Integer.parseInt(this.jLabel_tuno1.getText()),-1," ", liga.getCaminho()).setVisible(true);
            this.dispose();
        }else
            JOptionPane.showMessageDialog(null, "Seleciona um turno na tabela", "Aviso", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_jPanel24MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int row = this.jTable_todos_turnos.getSelectedRow();
        if (row>-1)
        {
            this.iduserTuno = Integer.parseInt(this.jTable_todos_turnos.getValueAt(row, 17).toString());
            this.jLabel_tuno1.setText(this.jTable_todos_turnos.getValueAt(row, 0).toString());
            new FecharTurno(this.iduserTuno, Double.parseDouble(this.jTable_todos_turnos.getValueAt(row, 13).toString()), 
                    Integer.parseInt(this.jLabel_tuno1.getText()),-1," ", liga.getCaminho()).setVisible(true);
            this.dispose();
        }else
            JOptionPane.showMessageDialog(null, "Seleciona um turno na tabela", "Aviso", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jInternalFrame1.setVisible(true);
        this.historico.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registo_de_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registo_de_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registo_de_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registo_de_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registo_de_turno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bancos_h;
    private javax.swing.JLabel entrada_em_caixa_h;
    private javax.swing.JLabel fatura_h;
    private javax.swing.JLabel fatura_recibo_h;
    private javax.swing.JInternalFrame historico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_Filtrar;
    private javax.swing.JComboBox<String> jComboBox_Filtrar;
    private javax.swing.JComboBox<String> jComboBox_OrdenarServico;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Saldo;
    private javax.swing.JLabel jLabel_Saldo1;
    private javax.swing.JLabel jLabel_abertura_h;
    private javax.swing.JLabel jLabel_estado_h;
    private javax.swing.JLabel jLabel_fecho_h;
    private javax.swing.JLabel jLabel_info;
    private javax.swing.JLabel jLabel_informado;
    private javax.swing.JLabel jLabel_informado1;
    private javax.swing.JLabel jLabel_quebra;
    private javax.swing.JLabel jLabel_quebra1;
    private javax.swing.JLabel jLabel_tuno1;
    private javax.swing.JLabel jLabel_turno;
    private javax.swing.JLabel jLabel_turno4;
    private javax.swing.JLabel jLabel_utlilizador3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_todos_turnos;
    private javax.swing.JTextField jTextField_Filtrar;
    private javax.swing.JLabel nota_de_credito_h;
    private javax.swing.JLabel nota_de_pagamento_h;
    private javax.swing.JLabel numerario_h;
    private javax.swing.JLabel recibo_h;
    private javax.swing.JLabel saida_de_caixa_h;
    private javax.swing.JLabel saldo_atual_h;
    private javax.swing.JLabel saldo_informado_h;
    private javax.swing.JLabel saldo_inicial_h;
    // End of variables declaration//GEN-END:variables

    public void PreencherTable(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nº", "Utilizador",
            "Factura",
            "Recibo ",
            "Factura recibo ",
            "Saida de caixa ",
            "Entrada em caixa ",
            "Nota de credito ",
            "Nota de pagamento  ",
            "Numerário  ",
            "Banco  ",
            "Saldo inicial  ",
            "Saldo ",
            "Informado",
            "Estado", "D. Abertura  ", "D. Fecho  ", "cod"};
        liga.conexao();
        liga.executeSql(Sql);

        try {
            if(liga.rs.first())
            do {
                boolean estado = liga.rs.getBoolean("estado");
                String Sestado = "Fechado";
                if (estado) {
                    Sestado = "Aberto";
                }

                dados.add(new Object[]{
                    liga.rs.getString("numero"),
                    liga.rs.getString("nome"),
                    liga.rs.getString("fatura"),
                    liga.rs.getString("recibo"),
                    liga.rs.getString("fatura_recibo"),
                    liga.rs.getString("saida_de_caixa"),
                    liga.rs.getString("entrada_em_caixa"),
                    liga.rs.getString("nota_de_credito"),
                    liga.rs.getString("nota_de_pagamento"),
                    liga.rs.getString("numerario"),
                    liga.rs.getString("bancos"),
                    liga.rs.getString("saldo_inicial"),
                    liga.rs.getString("saldo_atual"),
                    liga.rs.getString("saldo_final"),
                    Sestado,
                    liga.rs.getString("data_entrada") + " " + liga.rs.getString("hora_entrada"),
                    liga.rs.getString("data_saida") + " " + liga.rs.getString("horasaida"),
                    liga.rs.getString("idturno")
                });
            } while (liga.rs.next());
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(rootPane, "Dados não encntrados\n"+ex, "Aviso", JOptionPane.ERROR_MESSAGE);
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
        };

        jTable_todos_turnos.setModel(modelo);

        jTable_todos_turnos.getColumnModel()
                .getColumn(0).setPreferredWidth(70);
        jTable_todos_turnos.getColumnModel()
                .getColumn(0).setResizable(true);
//        jTableSevico.getColumnModel().getColumn(1).setPreferredWidth(235);
//        jTableSevico.getColumnModel().getColumn(1).setResizable(true);
//        jTableSevico.getColumnModel().getColumn(2).setPreferredWidth(70);
//        jTableSevico.getColumnModel().getColumn(2).setResizable(true);
//        jTableSevico.getColumnModel().getColumn(3).setPreferredWidth(255);
//        jTableSevico.getColumnModel().getColumn(3).setResizable(true);
//        jTableSevico.getColumnModel().getColumn(4).setPreferredWidth(70);
//        jTableSevico.getColumnModel().getColumn(4).setResizable(true);
//        jTableSevico.getColumnModel().getColumn(5).setPreferredWidth(70);
//        jTableSevico.getColumnModel().getColumn(5).setResizable(true);

        jTable_todos_turnos.getTableHeader()
                .setReorderingAllowed(false);
        jTable_todos_turnos.setAutoResizeMode(jTable_todos_turnos.AUTO_RESIZE_ALL_COLUMNS);
//        jTableSevico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        liga.deconecta();
    }

    void Verif(String s, String in) {
        
        this.jLabel_Saldo1.setText(this.exte.Chang(s) + this.exte.getMeoda());
        this.jLabel_informado1.setText(this.exte.Chang(in) + this.exte.getMeoda());
        double result = Double.parseDouble(in) - Double.parseDouble(s);
        this.jLabel_quebra1.setText(this.exte.Chang(Double.toString(result)) + this.exte.getMeoda());
    }
}
